node {
   def commit_id
   
    environment {
           dockerImage = 'test123'
    }
   
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       sh 'npm install --only=dev'
       sh 'npm test'
     }
   }
   stage('docker build/push') {
     script {
            dockerImage = docker.build
            docker.build('nodeappdemo')
        }
   }
}
